name: Pull from Lokalise

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Pull from Lokalise
        uses: lokalise/lokalise-pull-action@v3.0.0
        with:
          api_token: ${{ secrets.LOKALISE_API_TOKEN }}
          project_id: 8421778667e2dd2bc61ff8.47567322
          flat_naming: true
          base_lang: en
          file_format: json
